# Generated by Django 5.2.3 on 2025-06-21 20:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('salary', 'Salary'), ('cleaning', 'Cleaning'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20, verbose_name='category')),
                ('expense_date', models.DateField(verbose_name='expense date')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='invoice number')),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='invoices/', verbose_name='invoice image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='payment date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='cash', max_length=20, verbose_name='payment method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='transaction ID')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='receipt image')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentDues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='paid amount')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=10, verbose_name='status')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='late fee')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='last payment date')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='buildings.apartment')),
            ],
            options={
                'verbose_name': 'Apartment Dues',
                'verbose_name_plural': 'Apartment Dues',
            },
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('month', models.PositiveSmallIntegerField(verbose_name='month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, verbose_name='late fee percentage')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Dues',
                'verbose_name_plural': 'Dues',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
