# Generated by Django 5.2.3 on 2025-06-21 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartmentdues',
            name='dues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_dues', to='payments.dues'),
        ),
        migrations.AddField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='buildings.building'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='apartment_dues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.apartmentdues'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dues',
            unique_together={('building', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='apartmentdues',
            unique_together={('dues', 'apartment')},
        ),
    ]
