# Generated by Django 5.2.1 on 2025-07-07 15:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'email'], 'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_announcements',
            field=models.BooleanField(default=False, verbose_name='duyuru oluşturabilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_complaints',
            field=models.BooleanField(default=False, verbose_name='şikayetleri yönetebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_financial_reports',
            field=models.BooleanField(default=False, verbose_name='mali raporları görüntüleyebilir'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='şehir'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='doğum tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='e-posta doğrulandı'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='acil durum iletişim adı'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='acil durum telefonu'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Tam Zamanlı'), ('part_time', 'Yarı Zamanlı'), ('contract', 'Sözleşmeli'), ('temporary', 'Geçici')], max_length=20, null=True, verbose_name='istihdam türü'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='işe giriş tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='doğrulanmış hesap'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'İngilizce')], default='tr', max_length=10, verbose_name='dil'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='son giriş IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(default=0, verbose_name='giriş sayısı'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='TC kimlik no'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='telefon doğrulandı'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='posta kodu'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maaş'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Istanbul', max_length=50, verbose_name='zaman dilimi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-posta adresi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='telefon numarası'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='profil resmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Yönetici'), ('resident', 'Sakin'), ('caretaker', 'Kapıcı'), ('security', 'Güvenlik')], default='resident', max_length=20, verbose_name='rol'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Giriş'), ('logout', 'Çıkış'), ('profile_update', 'Profil Güncelleme'), ('password_change', 'Şifre Değiştirme'), ('complaint_create', 'Şikayet Oluşturma'), ('payment_made', 'Ödeme Yapma'), ('announcement_view', 'Duyuru Görüntüleme'), ('other', 'Diğer')], max_length=50, verbose_name='aktivite türü')),
                ('description', models.TextField(blank=True, null=True, verbose_name='açıklama')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='kullanıcı aracısı')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Aktivitesi',
                'verbose_name_plural': 'Kullanıcı Aktiviteleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('receive_sms_notifications', models.BooleanField(default=False, verbose_name='SMS bildirimi al')),
                ('receive_email_notifications', models.BooleanField(default=True, verbose_name='E-posta bildirimi al')),
                ('share_contact_info', models.BooleanField(default=True, verbose_name='İletişim bilgilerini paylaş')),
                ('show_profile_to_neighbors', models.BooleanField(default=True, verbose_name='Profili komşulara göster')),
                ('allow_direct_messages', models.BooleanField(default=True, verbose_name='Doğrudan mesajlara izin ver')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='biyografi')),
                ('interests', models.CharField(blank=True, max_length=200, null=True, verbose_name='ilgi alanları')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='meslek')),
                ('family_members', models.PositiveIntegerField(default=1, verbose_name='aile üyesi sayısı')),
                ('has_pets', models.BooleanField(default=False, verbose_name='evcil hayvan var')),
                ('pet_details', models.TextField(blank=True, null=True, verbose_name='evcil hayvan detayları')),
                ('has_vehicle', models.BooleanField(default=False, verbose_name='araç var')),
                ('vehicle_details', models.TextField(blank=True, null=True, verbose_name='araç detayları')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
