# Generated by Django 5.2.3 on 2025-06-21 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID number')),
                ('purpose', models.CharField(max_length=255, verbose_name='purpose of visit')),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='arrival time')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='departure time')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='vehicle plate')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='tracking number')),
                ('sender', models.CharField(blank=True, max_length=255, null=True, verbose_name='sender')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='status')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='received at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('delivery_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='delivery signature')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='buildings.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-received_at'],
            },
        ),
    ]
