# Generated by Django 5.2.3 on 2025-06-21 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='received_by',
            field=models.ForeignKey(limit_choices_to={'role': 'caretaker'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='buildings.apartment'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='buildings.building'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='recorded_by',
            field=models.ForeignKey(limit_choices_to={'role': 'caretaker'}, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
