# Generated by Django 5.2.3 on 2025-06-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1-5, where 5 is highest priority', verbose_name='priority')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one_time', 'One Time')], default='one_time', max_length=20, verbose_name='frequency')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='recurrence end date')),
                ('completion_notes', models.TextField(blank=True, null=True, verbose_name='completion notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_images/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task Image',
                'verbose_name_plural': 'Task Images',
            },
        ),
    ]
