# Generated by Django 5.2.3 on 2025-06-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaint_comments/', verbose_name='attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Complaint Comment',
                'verbose_name_plural': 'Complaint Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('noise', 'Noise'), ('cleanliness', 'Cleanliness'), ('security', 'Security'), ('parking', 'Parking'), ('neighbor', 'Neighbor'), ('other', 'Other')], default='maintenance', max_length=20, verbose_name='category')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=20, verbose_name='status')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1-5, where 5 is highest priority', verbose_name='priority')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaints/', verbose_name='attachment')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='resolution notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='buildings.apartment')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
