# Generated by Django 5.2.3 on 2025-06-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(blank=True, max_length=10, null=True, verbose_name='block')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='floor')),
                ('number', models.CharField(max_length=10, verbose_name='number')),
                ('size_sqm', models.PositiveIntegerField(default=0, verbose_name='size (m²)')),
                ('bedroom_count', models.PositiveSmallIntegerField(default=1, verbose_name='bedroom count')),
                ('resident_type', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='owner', max_length=10, verbose_name='resident type')),
                ('is_occupied', models.BooleanField(default=True, verbose_name='is occupied')),
                ('occupant_count', models.PositiveSmallIntegerField(default=1, verbose_name='occupant count')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.TextField(verbose_name='address')),
                ('block_count', models.PositiveSmallIntegerField(default=1, verbose_name='block count')),
                ('floors_per_block', models.PositiveSmallIntegerField(default=1, verbose_name='floors per block')),
                ('apartments_per_floor', models.PositiveSmallIntegerField(default=1, verbose_name='apartments per floor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
    ]
