# Generated by Django 5.2.1 on 2025-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='common_areas',
            field=models.TextField(blank=True, help_text='Description of common areas like garden, pool, gym, etc.', null=True, verbose_name='common areas'),
        ),
        migrations.AddField(
            model_name='building',
            name='construction_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='construction year'),
        ),
        migrations.AddField(
            model_name='building',
            name='energy_efficiency_class',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='energy efficiency class'),
        ),
        migrations.AddField(
            model_name='building',
            name='total_area_sqm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='total area (m²)'),
        ),
    ]
