# Generated by Django 5.2.1 on 2025-07-02 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlık')),
                ('message', models.TextField(verbose_name='mesaj')),
                ('notification_type', models.CharField(choices=[('info', 'Bilgi'), ('success', 'Başarılı'), ('warning', 'Uyarı'), ('error', 'Hata')], default='info', max_length=10, verbose_name='bildirim tipi')),
                ('is_read', models.BooleanField(default=False, verbose_name='okundu mu')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='bağlantı')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='oluşturulma tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
