# Generated by Django 5.2.1 on 2025-07-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_common_areas_building_construction_year_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Oluşturuldu'), ('read', 'Okundu'), ('dismissed', 'Kapatıldı'), ('email_sent', 'E-posta Gönderildi'), ('sms_sent', 'SMS Gönderildi'), ('failed', 'Başarısız')], max_length=50, verbose_name='eylem')),
                ('details', models.TextField(blank=True, null=True, verbose_name='detaylar')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='zaman damgası')),
            ],
            options={
                'verbose_name': 'Bildirim Günlüğü',
                'verbose_name_plural': 'Bildirim Günlükleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='e-posta bildirimleri')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS bildirimleri')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='anlık bildirimler')),
                ('payment_notifications', models.BooleanField(default=True, verbose_name='ödeme bildirimleri')),
                ('announcement_notifications', models.BooleanField(default=True, verbose_name='duyuru bildirimleri')),
                ('complaint_notifications', models.BooleanField(default=True, verbose_name='şikayet bildirimleri')),
                ('package_notifications', models.BooleanField(default=True, verbose_name='paket bildirimleri')),
                ('maintenance_notifications', models.BooleanField(default=True, verbose_name='bakım bildirimleri')),
                ('security_notifications', models.BooleanField(default=True, verbose_name='güvenlik bildirimleri')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='sessiz saatler başlangıcı')),
                ('quiet_hours_end', models.TimeField(default='08:00', verbose_name='sessiz saatler bitişi')),
                ('weekend_notifications', models.BooleanField(default=True, verbose_name='hafta sonu bildirimleri')),
                ('digest_frequency', models.CharField(choices=[('immediately', 'Hemen'), ('hourly', 'Saatlik'), ('daily', 'Günlük'), ('weekly', 'Haftalık'), ('never', 'Hiçbir Zaman')], default='immediately', max_length=20, verbose_name='özet sıklığı')),
            ],
            options={
                'verbose_name': 'Bildirim Tercihi',
                'verbose_name_plural': 'Bildirim Tercihleri',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='isim')),
                ('category', models.CharField(choices=[('system', 'Sistem'), ('payment', 'Ödeme'), ('building', 'Bina'), ('complaint', 'Şikayet'), ('announcement', 'Duyuru'), ('package', 'Paket'), ('maintenance', 'Bakım'), ('security', 'Güvenlik')], max_length=20, verbose_name='kategori')),
                ('title_template', models.CharField(max_length=255, verbose_name='başlık şablonu')),
                ('message_template', models.TextField(verbose_name='mesaj şablonu')),
                ('email_template', models.TextField(blank=True, null=True, verbose_name='e-posta şablonu')),
                ('sms_template', models.TextField(blank=True, null=True, verbose_name='SMS şablonu')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif mi')),
            ],
            options={
                'verbose_name': 'Bildirim Şablonu',
                'verbose_name_plural': 'Bildirim Şablonları',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_required',
            field=models.BooleanField(default=False, verbose_name='eylem gerekli mi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='eylem metni'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='eylem URL'),
        ),
        migrations.AddField(
            model_name='notification',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='buildings.apartment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='kapatılma tarihi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='e-posta gönderilme tarihi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='son geçerlilik tarihi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_dismissed',
            field=models.BooleanField(default=False, verbose_name='kapatıldı mı'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False, verbose_name='e-posta gönderildi mi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sms_sent',
            field=models.BooleanField(default=False, verbose_name='SMS gönderildi mi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='ek bilgiler'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='okunma tarihi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SMS gönderilme tarihi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Bilgi'), ('success', 'Başarılı'), ('warning', 'Uyarı'), ('error', 'Hata'), ('urgent', 'Acil')], default='info', max_length=10, verbose_name='bildirim tipi'),
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='isim')),
                ('category', models.CharField(choices=[('system', 'Sistem'), ('payment', 'Ödeme'), ('building', 'Bina'), ('complaint', 'Şikayet'), ('announcement', 'Duyuru'), ('package', 'Paket'), ('maintenance', 'Bakım'), ('security', 'Güvenlik')], default='system', max_length=20, verbose_name='kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif mi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='açıklama')),
                ('priority', models.IntegerField(default=1, help_text='1=Düşük, 2=Orta, 3=Yüksek', verbose_name='öncelik')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_groups', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Bildirim Grubu',
                'verbose_name_plural': 'Bildirim Grupları',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationgroup'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
